# Generated by Django 5.0.4 on 2024-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_subtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
